##  EXAMPLE TO ADD AN APP TO TRAEFIK ##
##  This would add portainer, and Traefik will proxy the front end traffic coming in to portainer.domain.fun ##
##  This composer template makes use of environment variables.  You can create the needed variables by editing (as root) /etc/environment or replace the variables with static values ##
#### Variables or values needed ###
#DOMAINNAME root domain (domain.fun)
#DOCKERDIR - where do your apps live?  (something like /home/me/docker)

version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer  ##always name your containers
    restart: always
    command: -H unix:///var/run/docker.sock
#    ports:
#      - "XXXX:9000"  ## only needed if you want the container to listen on a port different from the default.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
      - ${DOCKERDIR}/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy ##docker network to join
    labels:  ##Traefik uses labels to dynamically configure itself
      - "traefik.enable=true"    ##enable Traefik to proxy
      - "traefik.backend=portainer"    ##name of the container on the backend
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"    ##TLD to use (like portainer.yourdomain.fun) 
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      - "traefik.port=9000"  ##port that Traefik should assign to this container (ie..what port does the container listen on?).  This is the port Traefik will forward the traffic to.
      - "traefik.docker.network=traefik_proxy"  ##docker network the container lives on.  Traefik cant proxy if it's not part of the same network  
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
networks:
  traefik_proxy:
    external: true ##this says you've already created the network